on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
name: Deploy
jobs:
  test:
    name: Upload Staging
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Upload Staging
        uses: SamKirkland/FTP-Deploy-Action@2.0.0
        env:
          FTP_SERVER: ${{ secrets.TEST_FTP_SERVER }}
          FTP_USERNAME: ${{ secrets.TEST_FTP_USERNAME }}
          FTP_PASSWORD: ${{ secrets.TEST_FTP_PASSWORD }}
          LOCAL_DIR: ./
          REMOTE_DIR: /public_html/github-action-test/
  production:
    name: Upload Production
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Upload Production
        uses: SamKirkland/FTP-Deploy-Action@2.0.0
        env:
          FTP_SERVER: ${{ secrets.FTP_SERVER }}
          FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
          LOCAL_DIR: ./
          REMOTE_DIR: /public_html/github-action-test/
